float32 vdd		# VDD ADC channel (uq12.4) Invalid/NotAvailable = 0xFFFFU or 4095.9375 (f32) or NaN
float32 temp	# Temperature sensor ADC channel (q11.4) Invalid/NotAvailable = 0x7FFFU or 2047.9375 (f32) or NaN
float32 vsub	# Substrate Voltage ADC Channel (uq12.4) Invalid/NotAvailable = 0xFFFFU or 4095.9375 (f32) or NaN
float32 vddl	# VDD VCSEL ADC Channel (uq12.4) Invalid/NotAvailable = 0xFFFFU or 4095.9375 (f32) or NaN
float32 iapd	# APD current ADC Channel (uq12.4) Invalid/NotAvailable = 0xFFFFU or 4095.9375 (f32) or NaN
float32 bgl		# Background Light Value in arbitrary units (uq12.4) estimated by the substrate voltage control 
				# task Invalid/NotAvailable = 0xFFFFU or 4095.9375 (f32) or NaN
float32 sna		# Shot Noise Amplitude in LSB units (uq12.4) Invalid/NotAvailable = 0xFFFFU or 4095.9375 (f32) or NaN